apiVersion: v1
kind: Service
metadata:
    name: "toptechaks-41ed"
    labels:
        app: "toptechaks-41ed"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "toptechaks-41ed"