on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: toptechregistry.azurecr.io
        username: ${{ secrets.acr_toptechregistry_username }}
        password: ${{ secrets.acr_toptechregistry_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t toptechregistry.azurecr.io/toptechaks:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push toptechregistry.azurecr.io/toptechaks:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_toptechaks_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep toptechaksb40d | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace toptechaksb40d`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: toptechaksb40d
        container-registry-url: toptechregistry.azurecr.io
        container-registry-username: ${{ secrets.acr_toptechregistry_username }}
        container-registry-password: ${{ secrets.acr_toptechregistry_password }}
        secret-name: toptechaksdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: toptechaksb40d
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          toptechregistry.azurecr.io/toptechaks:${{ github.sha }}
        imagepullsecrets: |
          toptechaksdockerauth
